// Gráficas de la Copa versionadas en public/copa-cata/: afiches, flyers, logos y
// placas, y los objetos que pasaron de mano en mano (credenciales, entradas,
// stickers, rótulos, fichas de cata y etiquetas de premio; ver MATERIAL_OBJETO
// en tipos.ts). Las recorta y convierte a webp salidas/copas/_scripts/07_graficas.py
// (repo de secretaría), que también lista las piezas que quedaron afuera y por
// qué; el texto de cada una (alt, detalle, fuente) se escribe a mano acá.
//
// Van tal como circularon, con sus logos y su ilustración: la Copa es parte de
// la cultura cannábica y la contamos sin esconderla detrás del tabú. Quedan
// afuera solo las placas de ganadores que imprimen apellidos.
//
// El alt describe la pieza sin nombrar marcas: de las marcas el sitio da solo
// la cantidad, y quien ve la imagen las lee en ella.
//
// Al reemplazar un arte hay que cambiar el NOMBRE del archivo: el optimizador
// de next/image cachea por URL (ver lib/vertical/laminas.ts).

import type { Grafica } from "./tipos";

export const GRAFICAS: Grafica[] = [
  {
    id: "2014-credencial-participante",
    edicion: 2014,
    tipo: "credencial",
    src: "/copa-cata/2014/2014-credencial-participante.webp",
    width: 951,
    height: 1177,
    alt: "Credencial de la 1ra Copa Cata, de fondo negro con una franja naranja arriba: el logo de la asociación, la leyenda «Socio Participante» y abajo los logos de cinco marcas que acompañaron.",
    detalle: "Socio participante",
    fuente: "credencial-2014",
  },
  {
    id: "2014-credencial-invitado",
    edicion: 2014,
    tipo: "credencial",
    src: "/copa-cata/2014/2014-credencial-invitado.webp",
    width: 953,
    height: 1177,
    alt: "Credencial de la 1ra Copa Cata, de fondo blanco con la misma franja naranja: el logo de la asociación, la leyenda «Socio/Invitado» en una banda negra y los logos de las mismas cinco marcas.",
    detalle: "Socio/Invitado",
    fuente: "credencial-2014",
  },
  {
    id: "2014-rotulo-muestra",
    edicion: 2014,
    tipo: "rotulo",
    src: "/copa-cata/2014/2014-rotulo-muestra.webp",
    width: 662,
    height: 333,
    alt: "Rótulo autoadhesivo de la 1ra Copa: «Muestra N° 1» y el sol del logo de la asociación, con su filete negro de corte.",
    fuente: "rotulos-2014",
  },
  {
    id: "2015-flyer",
    edicion: 2015,
    tipo: "flyer",
    src: "/copa-cata/2015/2015-flyer.webp",
    width: 720,
    height: 1020,
    alt: "Flyer de la 2da Copa Cata del Oeste: una copa negra sobre un fondo de letras de colores, con la fecha, sábado 11 de julio a las 12.",
    fuente: "fb-2015-06-20",
  },
  {
    id: "2015-flyer-final",
    edicion: 2015,
    tipo: "flyer",
    src: "/copa-cata/2015/2015-flyer-final.webp",
    width: 720,
    height: 1016,
    alt: "Versión final del flyer de la 2da Copa Cata del Oeste, con la franja de logos de las marcas que la acompañaron.",
    fuente: "fb-2015-07-06",
  },
  {
    id: "2016-afiche",
    edicion: 2016,
    tipo: "afiche",
    src: "/copa-cata/2016/2016-afiche.webp",
    width: 1131,
    height: 1600,
    alt: "Afiche de la 3ra Copa Cata del Oeste: una copa dorada con el logo de la asociación, entre hojas de cannabis ilustradas en rojo y amarillo sobre fondo negro. Sábado 16 de julio a las 12.",
    fuente: "afiche-2016",
  },
  {
    id: "2016-flyer-redes",
    edicion: 2016,
    tipo: "flyer",
    src: "/copa-cata/2016/2016-flyer-redes.webp",
    width: 1200,
    height: 630,
    alt: "Versión apaisada del afiche de la 3ra Copa, preparada para redes, con el logo de la asociación en el centro.",
    fuente: "web-0525",
  },
  {
    id: "2017-afiche",
    edicion: 2017,
    tipo: "afiche",
    src: "/copa-cata/2017/2017-afiche.webp",
    width: 1107,
    height: 1600,
    alt: "Afiche de la IV Copa Cata del Oeste dibujado como un boceto sobre papel envejecido: una copa a lápiz y dos plumas mecánicas. Sábado 15 de julio a las 12; abajo, la franja de logos de las marcas que acompañaron.",
    fuente: "afiche-2017",
  },
  {
    id: "2017-entrada",
    edicion: 2017,
    tipo: "entrada",
    src: "/copa-cata/2017/2017-entrada.webp",
    width: 1590,
    height: 682,
    alt: "Entrada de la IV Copa Cata del Oeste con el dibujo del afiche, una pluma mecánica con engranajes sobre papel envejecido: sábado 15 de julio, $400, «buena música, mucha comida, premios, sorteos y mucho más».",
    fuente: "entradas-2017",
  },
  {
    id: "2017-sticker",
    edicion: 2017,
    tipo: "sticker",
    src: "/copa-cata/2017/2017-sticker.webp",
    width: 823,
    height: 823,
    alt: "Sticker cuadrado de la IV Copa con el mismo dibujo: la pluma mecánica sobre papel envejecido, el logo de la asociación y «sábado 15 de julio».",
    fuente: "stickers-2017",
  },
  {
    id: "2017-ficha-cata",
    edicion: 2017,
    tipo: "ficha-cata",
    src: "/copa-cata/2017/2017-ficha-cata.webp",
    width: 1242,
    height: 1600,
    alt: "Ficha de cata en blanco de la Copa 2017: arriba las reglas —nadie tiene su propia muestra en la mesa, se puntúa del 1 al 10, dos tandas de cata— y abajo seis cuadros para anotar visual, textura, aroma, sabor y total de cada muestra.",
    fuente: "ficha-cata-2017",
  },
  {
    id: "2019-afiche",
    edicion: 2019,
    tipo: "afiche",
    src: "/copa-cata/2019/2019-afiche.webp",
    width: 1130,
    height: 1600,
    alt: "Afiche de la VI Copa Cata del Oeste: el nombre en letras amarillas enormes sobre hojas de cannabis en magenta y naranja. Domingo 14/7; abajo, la franja de logos de las marcas que acompañaron.",
    fuente: "afiche-2019",
  },
  {
    id: "2019-logo",
    edicion: 2019,
    tipo: "logo",
    src: "/copa-cata/2019/2019-logo.webp",
    width: 654,
    height: 579,
    alt: "Logo de la VI Copa Cata del Oeste: el nombre en letras gruesas naranjas y la silueta de una flor.",
    fuente: "logo-2019",
  },
  {
    id: "2019-ficha-cata",
    edicion: 2019,
    tipo: "ficha-cata",
    src: "/copa-cata/2019/2019-ficha-cata.webp",
    width: 1131,
    height: 1600,
    alt: "Ficha de cata en blanco de la VI Copa: seis cuadros para puntuar la presentación, el aroma en flor y picado y el sabor apagado y prendido de cada muestra, y un casillero aparte para la muestra ganadora de la «Copa Berenjena».",
    fuente: "ficha-cata-2019",
  },
  {
    id: "2021-flyer",
    edicion: 2021,
    tipo: "flyer",
    src: "/copa-cata/2021/2021-flyer.webp",
    width: 1200,
    height: 1500,
    alt: "Flyer de la VII Copa Cata del Oeste: una pareja ilustrada junto a la copa sobre fondo rojo; ella fuma y él arma. Domingo 7 de noviembre.",
    fuente: "flyer-2021",
  },
  {
    id: "2021-entrada",
    edicion: 2021,
    tipo: "entrada",
    src: "/copa-cata/2021/2021-entrada.webp",
    width: 1600,
    height: 695,
    alt: "Entrada de la VII Copa Cata del Oeste, con la ilustración del flyer: la pareja junto a la copa. Domingo 7 de noviembre.",
    fuente: "entrada-2021",
  },
  {
    id: "2021-rotulo-muestra",
    edicion: 2021,
    tipo: "rotulo",
    src: "/copa-cata/2021/2021-rotulo-muestra.webp",
    width: 1182,
    height: 591,
    alt: "Etiqueta para las muestras de la VII Copa: fondo rojo con guarda naranja y hojas en las esquinas, el nombre de la Copa, el sol del logo de la asociación y 2021, y la mitad derecha lisa.",
    fuente: "etiqueta-muestra-2021",
  },
  {
    id: "2021-premio-mejor-planta",
    edicion: 2021,
    tipo: "etiqueta-premio",
    src: "/copa-cata/2021/2021-premio-mejor-planta.webp",
    width: 1067,
    height: 1600,
    alt: "Etiqueta de premio de la VII Copa Cata del Oeste, 2021, en negro sobre blanco: «Mejor Planta, 1er puesto».",
    detalle: "Mejor Planta",
    fuente: "etiquetas-premios-2021",
  },
  {
    id: "2021-premio-equipo",
    edicion: 2021,
    tipo: "etiqueta-premio",
    src: "/copa-cata/2021/2021-premio-equipo.webp",
    width: 1067,
    height: 1600,
    alt: "Etiqueta de premio de la VII Copa Cata del Oeste, 2021, en negro sobre blanco: «Mención, Mejor Equipo de Trabajo».",
    detalle: "Mejor equipo de trabajo",
    fuente: "etiquetas-premios-2021",
  },
  {
    id: "2021-logo",
    edicion: 2021,
    tipo: "logo",
    src: "/copa-cata/2021/2021-logo.webp",
    width: 1600,
    height: 832,
    alt: "Logo de la VII Copa Cata del Oeste, con letras de estilo antiguo y dos hojas a los lados.",
    fuente: "logo-2021",
  },
  {
    id: "2021-ganadores-mejor-planta",
    edicion: 2021,
    tipo: "placa-ganadores",
    src: "/copa-cata/2021/2021-ganadores-mejor-planta.webp",
    width: 1080,
    height: 1080,
    alt: "Placa de resultados de la VII Copa con el premio a la Mejor Planta y su genética.",
    fuente: "fb-2021-11-10",
  },
  {
    id: "2021-ganadores-exterior",
    edicion: 2021,
    tipo: "placa-ganadores",
    src: "/copa-cata/2021/2021-ganadores-exterior.webp",
    width: 1080,
    height: 1080,
    alt: "Placa de resultados de la VII Copa con los cinco puestos de la categoría Exterior y sus genéticas.",
    fuente: "fb-2021-11-10",
  },
  {
    id: "2021-ganadores-menciones",
    edicion: 2021,
    tipo: "placa-ganadores",
    src: "/copa-cata/2021/2021-ganadores-menciones.webp",
    width: 1080,
    height: 1080,
    alt: "Placa de resultados de la VII Copa con la mención del jurado y la mención al equipo de trabajo.",
    fuente: "fb-2021-11-10",
  },
  {
    id: "2021-sponsors-presentan",
    edicion: 2021,
    tipo: "placa-sponsors",
    src: "/copa-cata/2021/2021-sponsors-presentan.webp",
    width: 1080,
    height: 1080,
    alt: "Placa «Presentan» de la VII Copa, con los logos de las marcas principales que la acompañaron.",
    fuente: "placas-sponsors-2021",
  },
  {
    id: "2021-sponsors-bancos",
    edicion: 2021,
    tipo: "placa-sponsors",
    src: "/copa-cata/2021/2021-sponsors-bancos.webp",
    width: 1080,
    height: 1080,
    alt: "Placa «Acompañan» de la VII Copa, con los logos de los bancos de semillas que la acompañaron.",
    fuente: "placas-sponsors-2021",
  },
  {
    id: "2021-sponsors-grows",
    edicion: 2021,
    tipo: "placa-sponsors",
    src: "/copa-cata/2021/2021-sponsors-grows.webp",
    width: 1081,
    height: 1081,
    alt: "Placa «Acompañan» de la VII Copa, con los logos de los comercios de cultivo que la acompañaron.",
    fuente: "placas-sponsors-2021",
  },
  {
    id: "2021-sponsors-medios",
    edicion: 2021,
    tipo: "placa-sponsors",
    src: "/copa-cata/2021/2021-sponsors-medios.webp",
    width: 1080,
    height: 1080,
    alt: "Placa «Acompañan» de la VII Copa, con los logos de tres marcas.",
    fuente: "placas-sponsors-2021",
  },
  {
    id: "2021-sponsors-mesa",
    edicion: 2021,
    tipo: "placa-sponsors",
    src: "/copa-cata/2021/2021-sponsors-mesa.webp",
    width: 1080,
    height: 1080,
    alt: "Placa «Acompañan» de la VII Copa, con los logos de dos marcas de accesorios.",
    fuente: "placas-sponsors-2021",
  },
  {
    id: "2021-sponsors-historia",
    edicion: 2021,
    tipo: "placa-sponsors",
    src: "/copa-cata/2021/2021-sponsors-historia.webp",
    width: 900,
    height: 1600,
    alt: "Placa de agradecimiento de la VII Copa, publicada en las historias, con el logo de la edición y las marcas que acompañaron.",
    fuente: "ig-historias-2021",
  },
  {
    id: "2022-credencial",
    edicion: 2022,
    tipo: "credencial",
    material: "papel",
    src: "/copa-cata/2022/2022-credencial.webp",
    width: 1200,
    height: 796,
    alt: "Credencial de participante de la 8va Copa Cata del Oeste: una tarjeta de papel con «Participante», la etiqueta con el número y el mote, «#39 - EL BRUJA», y el logo de la edición con la flor; abajo, «Utiliza este QR para identificarte en la aplicación».",
    detalle: "Participante",
    fuente: "credencial-2022",
  },
  {
    id: "2022-flyer",
    edicion: 2022,
    tipo: "flyer",
    src: "/copa-cata/2022/2022-flyer.webp",
    width: 1080,
    height: 1350,
    alt: "Flyer de la 8va Copa Cata del Oeste: una flor de cannabis dibujada con texturas de galaxia junto al nombre. Domingo 17/7 a las 12.",
    fuente: "flyer-2022",
  },
  {
    id: "2022-sponsor-principal-1",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsor-principal-1.webp",
    width: 900,
    height: 1600,
    alt: "Placa de sponsor principal de la 8va Copa, con el logo de una distribuidora para tiendas de cultivo.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsor-principal-2",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsor-principal-2.webp",
    width: 900,
    height: 1600,
    alt: "Placa de sponsor principal de la 8va Copa, con el logo ilustrado de una marca sobre fondo de galaxia.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsor-principal-3",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsor-principal-3.webp",
    width: 900,
    height: 1600,
    alt: "Placa de sponsor principal de la 8va Copa, con el logo de una tienda cannábica sobre fondo de galaxia.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsor-principal-4",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsor-principal-4.webp",
    width: 900,
    height: 1600,
    alt: "Placa de sponsor principal de la 8va Copa, con el logo de una revista cannábica sobre fondo de galaxia.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsor-principal-5",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsor-principal-5.webp",
    width: 900,
    height: 1600,
    alt: "Placa de sponsor principal de la 8va Copa, con el logo de una marca de cultivo sobre fondo estrellado.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsor-principal-6",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsor-principal-6.webp",
    width: 900,
    height: 1600,
    alt: "Placa de sponsor principal de la 8va Copa, con el logo de un servicio para tiendas de cultivo.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsors-1",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsors-1.webp",
    width: 900,
    height: 1600,
    alt: "Placa de la 8va Copa con los logos de ocho marcas que la acompañaron, sobre fondo de galaxia.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsors-2",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsors-2.webp",
    width: 900,
    height: 1600,
    alt: "Placa de la 8va Copa con los logos de nueve marcas que la acompañaron, sobre fondo de galaxia.",
    fuente: "ig-historias-2022",
  },
  {
    id: "2022-sponsors-3",
    edicion: 2022,
    tipo: "placa-sponsors",
    src: "/copa-cata/2022/2022-sponsors-3.webp",
    width: 900,
    height: 1600,
    alt: "Placa de la 8va Copa con los logos de diez bancos de semillas que la acompañaron.",
    fuente: "ig-historias-2022",
  },
];
