// English → Spanish national-team names. The shared DB (and the internal match
// API the CMS reads) stores country names in their canonical ENGLISH form, but
// articles are written in Spanish, so the deterministic digest must feed the
// model Spanish names — otherwise it anchors on "England" and writes it verbatim.
//
// This is a COPY of `apps/fulbo-web/lib/countries.ts` → `COUNTRY_NAME_ES`,
// duplicated on purpose: the CMS deliberately does NOT depend on `@fulbo/db`
// or the web app (see match-context.ts). Keep the two in sync.
const COUNTRY_NAME_ES: Record<string, string> = {
  Argentina: "Argentina",
  Brazil: "Brasil",
  France: "Francia",
  Germany: "Alemania",
  Italy: "Italia",
  Spain: "España",
  England: "Inglaterra",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",
  Uruguay: "Uruguay",
  Mexico: "México",
  Canada: "Canadá",
  Morocco: "Marruecos",
  Croatia: "Croacia",
  Netherlands: "Países Bajos",
  Portugal: "Portugal",
  Belgium: "Bélgica",
  Switzerland: "Suiza",
  Japan: "Japón",
  "South Korea": "Corea del Sur",
  "Korea Republic": "Corea del Sur",
  Senegal: "Senegal",
  Ghana: "Ghana",
  Cameroon: "Camerún",
  Australia: "Australia",
  "Costa Rica": "Costa Rica",
  Ecuador: "Ecuador",
  "Saudi Arabia": "Arabia Saudita",
  Iran: "Irán",
  Qatar: "Catar",
  Poland: "Polonia",
  Tunisia: "Túnez",
  Denmark: "Dinamarca",
  Serbia: "Serbia",
  Wales: "Gales",
  Colombia: "Colombia",
  Chile: "Chile",
  Peru: "Perú",
  Paraguay: "Paraguay",
  Venezuela: "Venezuela",
  Bolivia: "Bolivia",
  Sweden: "Suecia",
  Norway: "Noruega",
  Russia: "Rusia",
  Turkey: "Turquía",
  Egypt: "Egipto",
  Nigeria: "Nigeria",
  "Ivory Coast": "Costa de Marfil",
  "Cote d'Ivoire": "Costa de Marfil",
  Algeria: "Argelia",
  "South Africa": "Sudáfrica",
  "New Zealand": "Nueva Zelanda",
  Austria: "Austria",
  Scotland: "Escocia",
  Ukraine: "Ucrania",
  "Czech Republic": "República Checa",
  Czechia: "República Checa",
  Hungary: "Hungría",
  Romania: "Rumania",
  Bulgaria: "Bulgaria",
  Greece: "Grecia",
  Ireland: "Irlanda",
  "Republic of Ireland": "Irlanda",
  "Northern Ireland": "Irlanda del Norte",
  Slovakia: "Eslovaquia",
  Slovenia: "Eslovenia",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  Iceland: "Islandia",
  Finland: "Finlandia",
  Mali: "Malí",
  "Burkina Faso": "Burkina Faso",
  Guinea: "Guinea",
  Panama: "Panamá",
  Jamaica: "Jamaica",
  Honduras: "Honduras",
  "El Salvador": "El Salvador",
  Haiti: "Haití",
  "Trinidad and Tobago": "Trinidad y Tobago",
  China: "China",
  Iraq: "Irak",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  Uzbekistan: "Uzbekistán",
  Oman: "Omán",
  Syria: "Siria",
  Vietnam: "Vietnam",
  Thailand: "Tailandia",
  "North Korea": "Corea del Norte",
  "Korea DPR": "Corea del Norte",
  Kuwait: "Kuwait",
  Bahrain: "Baréin",
  Jordan: "Jordania",
  Lebanon: "Líbano",
  Palestine: "Palestina",
  India: "India",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabue",
  "Congo DR": "RD del Congo",
  "DR Congo": "RD del Congo",
  Congo: "Congo",
  Gabon: "Gabón",
  Angola: "Angola",
  Togo: "Togo",
  Benin: "Benín",
  Uganda: "Uganda",
  Kenya: "Kenia",
  Tanzania: "Tanzania",
  Ethiopia: "Etiopía",
  Sudan: "Sudán",
  Libya: "Libia",
  Mozambique: "Mozambique",
  Namibia: "Namibia",
  Botswana: "Botsuana",
  Malawi: "Malaui",
  "Cape Verde": "Cabo Verde",
  "Guinea-Bissau": "Guinea-Bisáu",
  "Equatorial Guinea": "Guinea Ecuatorial",
  "Sierra Leone": "Sierra Leona",
  Liberia: "Liberia",
  Gambia: "Gambia",
  Mauritania: "Mauritania",
  Madagascar: "Madagascar",
  Comoros: "Comoras",
  Mauritius: "Mauricio",
  Seychelles: "Seychelles",
  Djibouti: "Yibuti",
  Somalia: "Somalia",
  Eritrea: "Eritrea",
  "South Sudan": "Sudán del Sur",
  "Central African Republic": "República Centroafricana",
  Chad: "Chad",
  Niger: "Níger",
  Burundi: "Burundi",
  Rwanda: "Ruanda",
  Lesotho: "Lesoto",
  Eswatini: "Esuatini",
  "Sao Tome and Principe": "Santo Tomé y Príncipe",
  Curacao: "Curazao",
  Yugoslavia: "Yugoslavia",
  "West Germany": "Alemania Occidental",
  "East Germany": "Alemania Oriental",
  "Soviet Union": "Unión Soviética",
  Czechoslovakia: "Checoslovaquia",
};

/**
 * Localize a national-team name to Spanish. Unknown names (clubs, rare nations,
 * aliases not in the map) fall back to the original — better the raw value than
 * a blank. Safe to call on any team name.
 */
export function toEsCountry(name: string | null | undefined): string {
  if (!name) return "";
  return COUNTRY_NAME_ES[name] ?? name;
}
