#!/usr/bin/env bash
# Prints a ready-to-paste block of strong random secrets for .env (production).
# Usage: scripts/generate-prod-secrets.sh > /tmp/secrets.txt && review before saving.

set -euo pipefail

rand() { openssl rand -base64 32 | tr -d '\n='; }

cat <<EOF
# === Auto-generated by generate-prod-secrets.sh on $(date -Iseconds) ===

POSTGRES_PASSWORD=$(rand)
DATABASE_URL=postgresql://codelo:REPLACE_WITH_POSTGRES_PASSWORD_ABOVE@postgres:5432/codelo?schema=public

STRAPI_APP_KEYS=$(rand),$(rand),$(rand),$(rand)
STRAPI_API_TOKEN_SALT=$(rand)
STRAPI_ADMIN_JWT_SECRET=$(rand)
STRAPI_JWT_SECRET=$(rand)
STRAPI_TRANSFER_TOKEN_SALT=$(rand)
STRAPI_ENCRYPTION_KEY=$(rand)

INTERNAL_API_KEY=$(rand)

REDIS_PASSWORD=$(rand)
REDIS_URL=redis://:REPLACE_WITH_REDIS_PASSWORD_ABOVE@redis:6379

# OPENAI_API_KEY must be set manually (not auto-generated). Get one at
# https://platform.openai.com/api-keys
OPENAI_API_KEY=sk-replace-with-real-key

# Strapi CORS — set to your production origin(s), comma-separated.
CORS_ALLOWED_ORIGINS=https://cogollosdeloeste.com.ar

# Reminders:
#  - Replace REPLACE_WITH_POSTGRES_PASSWORD_ABOVE in DATABASE_URL with the actual value.
#  - Replace REPLACE_WITH_REDIS_PASSWORD_ABOVE in REDIS_URL with the actual value.
EOF
