// GENERADO por salidas/web-vieja/_import/generar_manifiesto.py — no editar a mano.
// Las notas del archivo histórico: las propias del sitio anterior (2014–2021), con su fecha original, y las nuevas que lo cuentan.
// Salen de lo que se preparó para importar al CMS; el slug final y las portadas del CMS, del estado de la importación.
import type { NotaArchivo } from "./tipos";

export const NOTAS: NotaArchivo[] = [
  {
    slug: "copa-cata-cogollos-del-oeste-2014",
    titulo: "Copa-Cata Cogollos del Oeste",
    excerpt:
      "Crónica de un participante de la primera Copa-Cata del Oeste, en el barrio de Flores: la previa, la cata por mesas y los premios.",
    autor: "Gato Volador",
    fecha: "2014-08-05T02:32:33-03:00",
    tipo: "cronica",
    viejoId: 10,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/copa_cata_2014_001_5335db03f4.webp",
      width: 800,
      height: 533,
      alt: "Flores sobre una ficha de puntuación de la cata, con una tijera y papelillos, Copa Cata del Oeste 2014",
      clase: "foto",
    },
    destacada: false,
  },
  {
    slug: "taller-pre-y-post-cosecha-jamaica-nice-2014",
    titulo: "La Pre y post - Cosecha by Jamaica Nice",
    excerpt:
      "Segunda parte de nuestro taller de indoor, dictado por Jamaica Nice en San Telmo: punto de corte, secado, curado y conservación de la cosecha.",
    autor: "Gato Volador",
    fecha: "2014-08-05T03:07:33-03:00",
    tipo: "cronica",
    viejoId: 11,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_0011_e189edcab3.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: ramas de cannabis recién cortadas sobre una bandeja, con una tijera de podar y una lupa",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "taller-de-genetica-y-polinizacion-jamaica-nice-2014",
    titulo: "Un taller de Genética Very Nice",
    excerpt:
      "El disertante Jamaica Nice nos tira de cabeza en el mundo de la genética, para terminar de entender lo que cultivamos, y estar un paso mas cerca de la raza propia.",
    autor: "Gato Volador",
    fecha: "2014-08-26T10:44:46-03:00",
    tipo: "cronica",
    viejoId: 34,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_0034_a3dec31bbf.webp",
      width: 960,
      height: 640,
      alt: "Asistentes de espaldas en sillas de colores frente a una diapositiva sobre cruces de genéticas, en el taller de polinización y genética de 2014",
      clase: "foto",
    },
    destacada: false,
  },
  {
    slug: "taller-de-cultivo-a-la-carta-jamaica-nice-2014",
    titulo: "Taller de Cultivo a la Carta con Jamaica Nice",
    excerpt:
      "Crónica del primer taller de «Cultivo a la Carta» de Cogollos del Oeste, el domingo 26 de octubre de 2014, con Jamaica Nice: planificación del cultivo, elección de genéticas y respuestas en forma de tips.",
    autor: "Gato Volador",
    fecha: "2014-11-12T14:07:14-03:00",
    tipo: "cronica",
    viejoId: 88,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_0088_533cef1bea.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una bandeja de plantines de cannabis, una pala de jardín, una regadera y sobres de semillas",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "taller-de-secado-y-curado-jamaica-nice-2015",
    titulo: "Taller de Secado y Curado by Jamaica Nice",
    excerpt:
      "Crónica del taller de secado y curado que dio Jamaica Nice el sábado 11 de abril de 2015: punto de corte, secado, curado y conservación.",
    autor: "Chori",
    fecha: "2015-04-28T01:17:28-03:00",
    tipo: "cronica",
    viejoId: 154,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_0154_9c59c1badb.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un secadero de malla con flores de cannabis, frascos de curado y un higrómetro",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "cronica-copa-cata-del-oeste-2015",
    titulo: "Crónica Copa-Cata del Oeste 2015",
    excerpt: "Enterate qué pasó y quiénes fueron los ganadores de la única del oeste.",
    autor: "Gato Volador",
    fecha: "2015-07-22T14:17:36-03:00",
    tipo: "cronica",
    viejoId: 187,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/copa_cata_2015_021_4c8e976165.webp",
      width: 1068,
      height: 712,
      alt: "Bandera de la asociación sobre una mesa con copas, productos de cultivo y remeras, Copa Cata del Oeste 2015",
      clase: "foto",
    },
    destacada: false,
  },
  {
    slug: "entrevista-marcelo-morante-medico-solidario",
    titulo: "Entrevista al Dr. Marcelo Morante un ejemplo de medico solidario",
    excerpt:
      "El equipo de Cogollos del Oeste visitó al Dr. Marcelo Morante, que nos contó su experiencia con el cannabis medicinal.",
    autor: "Gato Volador",
    fecha: "2015-11-17T11:16:28-03:00",
    tipo: "entrevista",
    viejoId: 277,
    idsFusionados: [],
    entrevistado: "Dr. Marcelo Morante",
    portada: {
      src: "/cms/uploads/archivo_0277_ab97c019a3.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un maletín de médico abierto, un estetoscopio, un gotero de vidrio y una rama de cannabis",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-fundacion-daya-expo-cannabis-uruguay-2015",
    titulo: "Entrevista a Fundación DAYA en la Expo Cannabis Uruguay 2015",
    excerpt:
      "En la Expo Cannabis Uruguay 2015 entrevistamos a la directora ejecutiva de Fundación DAYA, la organización chilena que impulsó el cambio de ley en su país.",
    autor: "Gato Volador",
    fecha: "2015-12-26T11:57:33-03:00",
    tipo: "entrevista",
    viejoId: 293,
    idsFusionados: [],
    entrevistado: "Fundación DAYA",
    portada: {
      src: "/cms/uploads/archivo_0293_a8e7a9efaa.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una carpa de exposición con banderines y plantas de cannabis, con la rambla de Montevideo al fondo",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "marcha-mundial-de-la-marihuana-2016",
    titulo: "Marcha Mundial de la Marihuana 2016",
    excerpt:
      "Crónica de la Marcha Mundial de la Marihuana 2016: la cabecera colmada por madres, padres y usuarios medicinales y dos consignas, «No más presos por plantar» y «El dolor no espera».",
    autor: "Gato Volador",
    fecha: "2016-05-16T13:10:15-03:00",
    tipo: "cronica",
    viejoId: 441,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_0441_7ea343e8f8.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: banderas en alto frente a la cúpula del Congreso de la Nación, con hojas de cannabis en el viento",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "modificaciones-ley-de-drogas-23737-2016",
    titulo: "Modificaciones en la Ley de drogas 23.737",
    excerpt:
      "La reforma de la Ley 23.737 publicada en el Boletín Oficial el 8 de noviembre de 2016 cambió los artículos sobre precursores químicos, pero dejó intacta la penalización de la tenencia y del cultivo de cannabis.",
    autor: "Chori",
    fecha: "2016-11-10T15:29:50-03:00",
    tipo: "informe",
    viejoId: 869,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_informe_44292b235e.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: documentos atados con cinta y lacre, y una lupa sobre una hoja de cannabis",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "cultivo-cannabico-solidario-entrevista-el-pirata",
    titulo:
      "Cultivo cannábico solidario: “No somos criminales, cultivamos nuestra propia medicina”",
    excerpt:
      "Entrevista a «El Pirata», cultivador solidario de cannabis medicinal y activista por la legalización, con testimonios de usuarios medicinales.",
    autor: "Laura Achiou",
    fecha: "2017-09-20T20:31:37-03:00",
    tipo: "entrevista",
    viejoId: 983,
    idsFusionados: [],
    entrevistado: "«El Pirata»",
    portada: {
      src: "/cms/uploads/archivo_0983_22a231de24.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un sombrero de pirata sobre un banco de jardín, junto a plantas de cannabis en macetas y goteros",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-leo-activista-ciberactivismo-cannabico",
    titulo: '"Agarraban a los boludos pero a los grandes no les cayeron"',
    excerpt:
      "Entrevista a Leo, activista cannábico desde fines de los noventa: sus primeras semillas, la causa que le iniciaron por su sitio web y lo que le falta al movimiento. Reúne las dos partes publicadas en octubre de 2017.",
    autor: "Santiago",
    fecha: "2017-10-12T21:14:39-03:00",
    tipo: "entrevista",
    viejoId: 985,
    idsFusionados: [987, 989],
    entrevistado: "Leo",
    portada: {
      src: "/cms/uploads/archivo_0985_8732ac571b.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una computadora de fines de los noventa con una hoja de cannabis en la pantalla, un módem y disquetes",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-emilio-ruchansky-un-mundo-con-drogas",
    titulo: '"Cuando vos subjetivás a la sustancia, objetivás a la persona"',
    excerpt:
      "Entrevista a Emilio Ruchansky, periodista de la revista THC y autor de «Un mundo con drogas», sobre las políticas alternativas a la prohibición en el mundo y la situación en la Argentina.",
    autor: "Santiago",
    fecha: "2017-12-07T16:46:37-03:00",
    tipo: "entrevista",
    viejoId: 991,
    idsFusionados: [],
    entrevistado: "Emilio Ruchansky",
    portada: {
      src: "/cms/uploads/archivo_0991_0bb2684bd5.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un globo terráqueo antiguo rodeado por una corona de plantas medicinales, junto a un libro abierto",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-alvaro-sauri-cuidados-paliativos-cannabis",
    titulo: '"Quizás el más importante para mí es el de los cultivadores solidarios"',
    excerpt:
      "Entrevista al Dr. Álvaro Sauri, a cargo de cuidados paliativos del Instituto de Oncología Ángel H. Roffo, sobre el uso terapéutico del cannabis y la Ley 27.350 a un año de su sanción.",
    autor: "Santiago",
    fecha: "2018-04-05T16:49:01-03:00",
    tipo: "entrevista",
    viejoId: 997,
    idsFusionados: [],
    entrevistado: "Dr. Álvaro Sauri",
    portada: {
      src: "/cms/uploads/archivo_0997_3897ea18d0.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una mesa de luz junto a una ventana, con una lámpara, un vaso de agua, un gotero y una rama de cannabis",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-burix-mechoso-investigacion-cannabis-udelar",
    titulo: '"El objetivo fue hacer algo útil para la gente"',
    excerpt:
      "Entrevista a Burix Mechoso, biólogo e investigador de la Universidad de la República (Montevideo, Uruguay), sobre la investigación del cannabis y la regulación uruguaya.",
    autor: "Santiago",
    fecha: "2018-06-18T16:38:01-03:00",
    tipo: "entrevista",
    viejoId: 1001,
    idsFusionados: [],
    entrevistado: "Burix Mechoso",
    portada: {
      src: "/cms/uploads/archivo_1001_971fa3d450.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un microscopio de bronce, tubos de ensayo, cajas de Petri y una hoja de cannabis bajo un portaobjetos",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-maria-victoria-baca-paunero-defensora",
    titulo: '"Se persigue más a las mujeres y se criminaliza más a las mujeres que a los hombres"',
    excerpt:
      "Entrevista a María Victoria Baca Paunero, defensora oficial en lo Criminal y Correccional de Lomas de Zamora, sobre la política de drogas vista desde el Poder Judicial y con perspectiva de género.",
    autor: "Santiago",
    fecha: "2018-08-14T18:16:59-03:00",
    tipo: "entrevista",
    viejoId: 1007,
    idsFusionados: [],
    entrevistado: "María Victoria Baca Paunero",
    portada: {
      src: "/cms/uploads/archivo_1007_c81fc4a32b.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una balanza en equilibrio con una hoja de cannabis y flores silvestres, junto a libros de leyes",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "entrevista-nectar-extraccion-supercritica",
    titulo: '"Queríamos hacer algo que (...) lo pudiésemos poner al servicio de la sociedad"',
    excerpt:
      "Entrevista a Franco, del equipo de Néctar, una máquina de extracción con dióxido de carbono supercrítico que nació como tesis de diseño industrial en la universidad pública.",
    autor: "Santiago",
    fecha: "2019-06-07T17:43:22-03:00",
    tipo: "entrevista",
    viejoId: 1009,
    idsFusionados: [],
    entrevistado: "Franco",
    portada: {
      src: "/cms/uploads/archivo_1009_7946aef517.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una máquina de extracción con dióxido de carbono supercrítico, con manómetros, y un frasquito de extracto",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "dia-internacional-del-orgullo-lgtbiq-2021",
    titulo: "28 de junio - Día Internacional del Orgullo LGTBIQ+",
    excerpt: "En el armario sólo se guardan las flores.",
    autor: "Cogollos del Oeste",
    fecha: "2021-06-28T21:49:07-03:00",
    tipo: "pronunciamiento",
    viejoId: 1102,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_1102_5197dff7a4.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un ropero antiguo abierto, desbordado de flores y ramas de cannabis",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "justicia-por-miguel-2021",
    titulo: "Justicia por Miguel",
    excerpt:
      "A ocho años de la muerte de Miguel en la comisaría 1ª de Pilar, pedimos justicia: el Estado es responsable.",
    autor: "Cogollos del Oeste",
    fecha: "2021-09-09T19:25:02-03:00",
    tipo: "pronunciamiento",
    viejoId: 1145,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_pronunciamiento_258583b464.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: un puño en alto con un ramo de flores y rayos de sol",
      clase: "ilustracion",
    },
    destacada: false,
  },
  {
    slug: "cronologia-2014-2017",
    titulo: "Cronología 2014-2017: lo que fuimos siguiendo",
    excerpt:
      "De los primeros registros de cultivo en Uruguay a la Ley 27.350: los hitos sobre cannabis que seguimos y compartimos entre 2014 y 2017, cada uno con el enlace a su fuente original.",
    autor: "Cogollos del Oeste",
    fecha: "2026-10-07T02:32:40-03:00",
    tipo: "cronologia",
    viejoId: null,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_cronologia_c65c478561.webp",
      width: 1600,
      height: 893,
      alt: "Grabado a dos tintas: una enredadera con medallones que avanza hacia un sol naciente",
      clase: "ilustracion",
    },
    destacada: true,
  },
  {
    slug: "los-monos-de-heath",
    titulo: "Los monos de Heath: cómo nació el mito de las neuronas muertas",
    excerpt:
      "En los años setenta, un psiquiatra de la Universidad de Tulane expuso monos rhesus al humo de marihuana y concluyó que el cannabis dañaba el cerebro. Contamos qué hizo, qué le objetaron y qué encontraron los estudios que vinieron después.",
    autor: "Cogollos del Oeste",
    fecha: "2026-10-07T02:32:42-03:00",
    tipo: "investigacion",
    viejoId: null,
    idsFusionados: [],
    entrevistado: null,
    portada: {
      src: "/cms/uploads/archivo_investigacion_04e0e9921b.webp",
      width: 1600,
      height: 888,
      alt: "Grabado a dos tintas: una máscara de gas, una campana de vidrio y un cerebro sobre una mesa de laboratorio, junto a una ventana abierta a la noche por la que sale un mono",
      clase: "ilustracion",
    },
    destacada: true,
  },
];
